import type { InfoItem } from './types';

export const mockData: InfoItem[] = [
  {
    id: 'garantia-konica',
    type: 'note',
    title: 'Garantía Konica',
    content: `Sitio web: Www.kminfo.biz\nUsuario: MARROYO\nContraseña: maquelsa2008\n\nProcedimiento:\n1. Ir a Formularios -> Garantia\n2. Poner teléfono.\n3. Marcar si la persona de contacto es la misma.\n4. Poner persona con la que hemos hablado.\n5. Comentario: poner "enviar a maquelsa san sebastian".`,
    categories: ['konica', 'garantia', 'procedimientos'],
    createdAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'i-option',
    type: 'note',
    title: 'I-option',
    content: `Info hub, carlos serrano, Maquelsa2008 información\nData movie, serv. Tecnico e install data system 2 segunda pagina`,
    categories: ['i-option', 'konica'],
    createdAt: '2024-01-02T10:00:00Z',
  },
  {
    id: 'amenabar-impresora',
    type: 'password',
    title: 'Credenciales Impresora Amenabar',
    content: `Usuario: impresora\nPass: Amenabar1`,
    categories: ['amenabar', 'contraseñas', 'impresoras'],
    createdAt: '2024-01-03T10:00:00Z',
  },
  {
    id: 'soporte-samsung',
    type: 'note',
    title: 'Soporte Samsung',
    content: `Teléfono: 917547054\nPin: 90196\nPin alternativo: 91009`,
    categories: ['samsung', 'soporte'],
    createdAt: '2024-01-04T10:00:00Z',
  },
  {
    id: 'ricoh-reset',
    type: 'note',
    title: 'Códigos Servicio Ricoh',
    content: `Clear 107 stop\n\nStop + 0 + C`,
    categories: ['ricoh', 'procedimientos', 'servicio'],
    createdAt: '2024-01-05T10:00:00Z',
  },
  {
    id: 'exportar-libreta-direcciones',
    type: 'note',
    title: 'Exportar libreta direcciones Konica',
    content: `Softswitch 72 al 04\nAdmin\nCopia de seguridad memoria Externado`,
    categories: ['konica', 'procedimientos', 'libreta-direcciones'],
    createdAt: '2024-01-06T10:00:00Z',
  },
  {
    id: 'desbloqueo-konica-c3350',
    type: 'note',
    title: 'Desbloqueo Konica C3350',
    content: `Menu, Contador, teclado:\nStop 09317 ta 5 min itxoin`,
    categories: ['konica', 'procedimientos', 'desbloqueo'],
    createdAt: '2024-01-07T10:00:00Z',
  },
  {
    id: 'codigos-servicio-hp-samsung',
    type: 'note',
    title: 'Códigos de servicio HP y Samsung',
    content: `https://medium.com/@pinnaclenetwork/hp-printer-service-codes-402996fa9a3c`,
    categories: ['hp', 'samsung', 'servicio', 'enlaces'],
    createdAt: '2024-01-08T10:00:00Z',
  },
  {
    id: 'verificar-total-konica',
    type: 'note',
    title: 'Verificar total Konica',
    content: `Swift swich 227 al 00`,
    categories: ['konica', 'procedimientos'],
    createdAt: '2024-01-09T10:00:00Z',
  },
  {
    id: 'admin-passwords',
    type: 'password',
    title: 'Contraseñas Admin (Genéricas)',
    content: `lankidego@2010\nlankidego@2011\nlankidego@2012\nlankidego@2013\nlankidego@2014`,
    categories: ['contraseñas', 'admin'],
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'maquelsa-correo',
    type: 'password',
    title: 'Acceso Correo Maquelsa',
    content: `URL: mail.maquelsa.com/correoweb\nPassword: 32HTZ2008`,
    categories: ['maquelsa', 'contraseñas', 'correo'],
    createdAt: '2024-01-11T10:00:00Z',
  },
  {
    id: 'airtable-acceso',
    type: 'password',
    title: 'Acceso Airtable',
    content: `Usuario: mirastorza@maquelsa.com\nPassword: 32HTZ2008`,
    categories: ['airtable', 'contraseñas'],
    createdAt: '2024-01-12T10:00:00Z',
  },
  {
    id: 'cruz-roja-acceso',
    type: 'password',
    title: 'Acceso Cruz Roja',
    content: `Dominio: 99_CEN\nUsuario: mikel\nPassword: Azkuene99`,
    categories: ['cruz-roja', 'contraseñas'],
    createdAt: '2024-01-13T10:00:00Z',
  },
  {
    id: 'easo-motor-acceso',
    type: 'password',
    title: 'Acceso EASO MOTOR / Oarsocar',
    content: `Usuario: su usuario\nPass: Easomotor1 (si es oarsocar Oarsocar1)\n\nMail:\nimpresora@easomotor.es -> 20Impresora02\nimpresora@oarsocar.com -> 30Impresora03\n\nSMTP: smtp.easomotor.es`,
    categories: ['easo-motor', 'oarsocar', 'contraseñas', 'correo'],
    createdAt: '2024-01-14T10:00:00Z',
  },
  {
    id: 'firmware-konica-c3100p',
    type: 'note',
    title: 'Firmware Konica C3100P',
    content: `Menu/counter/stop/b/b/stop/b/g\nb(bera)\ng(gora)`,
    categories: ['konica', 'procedimientos', 'firmware'],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'virtual-infodesain',
    type: 'note',
    title: 'Virtual Infodesain',
    content: `Mfc 35\nOracle 5.2`,
    categories: ['infodesain', 'oracle'],
    createdAt: '2024-01-16T10:00:00Z',
  },
  {
    id: 'zurriola-acceso',
    type: 'password',
    title: 'Acceso Zurriola',
    content: `Usuario: Administrador\nPassword: ZI.090678`,
    categories: ['zurriola', 'contraseñas'],
    createdAt: '2024-01-17T10:00:00Z',
  },
  {
    id: 'errenteria-musikal-acceso',
    type: 'password',
    title: 'Acceso Errenteria Musikal',
    content: `Usuario: .\\adminuser\nPassword: Auser55`,
    categories: ['errenteria-musikal', 'contraseñas'],
    createdAt: '2024-01-18T10:00:00Z',
  },
  {
    id: 'carza-motor-acceso',
    type: 'password',
    title: 'Acceso Carza Motor',
    content: `Usuario: Ventas\nPasswd: 123456`,
    categories: ['carza-motor', 'contraseñas'],
    createdAt: '2024-01-19T10:00:00Z',
  },
  {
    id: 'piezas-konica',
    type: 'note',
    title: 'Notas sobre piezas Konica',
    content: `Zona de influencia piezas konica -> C\nPiezas de segunda mano, en el parte poner p07`,
    categories: ['konica', 'piezas', 'procedimientos'],
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'konica-4000i-drum-reset',
    type: 'note',
    title: 'Reset de tambor Konica 4000i',
    content: `La maquina encendida, tapa delantera abierta, pulsar el boton OK 2 segundos y aparece para resetear, hay que darle a la flecha arriba.`,
    categories: ['konica', 'procedimientos', 'reset'],
    createdAt: '2024-01-21T10:00:00Z',
  },
  {
    id: 'konica-c300i-load-check',
    type: 'note',
    title: 'Load Check para ruidos en Konica C300i',
    content: `Para ruidos en una c300i, el residual de arriba.\nState confirmation, load check (eskubiko atia iriki), start..., eskubiko atia itxi, ta 44 + ok\n\nFusor -> 45-1\nResidual -> 44-0`,
    categories: ['konica', 'procedimientos', 'diagnóstico'],
    createdAt: '2024-01-22T10:00:00Z',
  },
  {
    id: 'oauth-konica',
    type: 'note',
    title: 'Configurar Oauth 2.0 en Konica',
    content: `Actualizar firmware a gc2 (me ha pasado en una c251i)\nDesde la maquina, fisicamente, entrar en administrador, red, envio de correo, ahi aparece la opcion de habilitar oauth 2.0, desde la web no. Activar y seleccionar google por ejemplo si es de gmail.`,
    categories: ['konica', 'procedimientos', 'oauth', 'correo'],
    createdAt: '2024-01-23T10:00:00Z',
  },
  {
    id: 'anydesk-installer',
    type: 'application',
    title: 'Instalador de Anydesk',
    content: 'Cliente de escritorio remoto Anydesk para Windows. Versión 7.0.14.',
    categories: ['software', 'remoto', 'windows'],
    createdAt: '2024-02-01T10:00:00Z',
    downloadUrl: 'https://anydesk.com/es/downloads/windows',
  },
  {
    id: 'automatikoak-fichero1',
    type: 'application',
    title: 'Aldatu beharrekoa',
    content: 'Instalador MFC para cliente Automatikoak.',
    categories: ['automatikoak', 'cliente', 'instalador'],
    createdAt: '2024-03-05T11:00:00Z',
    downloadUrl: 'https://firebasestorage.googleapis.com/v0/b/infovault-reurt.firebasestorage.app/o/Automatikoak%2Fmfc.exe?alt=media&token=4c93dba5-4e92-434d-bdd0-5c3f768da1b2',
  },
  {
    id: 'automatikoak-fichero2',
    type: 'application',
    title: 'Istalatzailea',
    content: 'Segundo fichero de la carpeta Automatikoak.',
    categories: ['automatikoak', 'cliente'],
    createdAt: '2024-03-05T11:05:00Z',
    downloadUrl: 'https://firebasestorage.googleapis.com/v0/b/infovault-reurt.firebasestorage.app/o/Automatikoak%2FMFC.msi?alt=media&token=035cf019-caca-4070-ac65-c755661b7e7a',
  }
];
